### ISSUE TITLE
KAS/KJR strut destruction.

### ISSUE THREAD

**Issue by KAmaia** [ferram4/Kerbal-Joint-Reinforcement#12]
Not sure if this should go here or on the KAS issue tracker, so posting it in both places.  If a RS-C2 strut is place and linked with KJR installed, and the strut is linked to a docked vessel, one or both of the vessels will spontaneously deconstruct at physics load.  This includes: Timewarp, game load etc., rather annoying behaviour.  

KSP 1.1.3
Windows x64.

**Comment by ferram4** [comment]
If this is two vessels that have merged through docking and they're being destroyed, then this is my problem to handle, but I'd have to look into what's being done there.

If it's two vessels that haven't merged into a single vessel through docking that are somehow connected by a strut between them then it's on KAS's side.  KJR shouldn't be affecting joints that aren't within a single vessel.

**Comment by KAmaia** [comment]
It is two vessels that have merged through docking.    The procedure used was: Dock Two Shuttles -> EVA an Engineer -> Link the CS-R2 on the bottom of one shuttle's tail, to the one on the top of the other -> Timewarp -> Watch spontaneous Deconstruction.

Spontaneous Deconstruction will also occur if more than .05g is applied to either craft it atmosphere.  Not sure if it's related.

**Comment by ferram4** [comment]
Hey, if you have the opportunity and your save / craft is compatible with KSP 1.2, can you try the latest dev build and see if it fixes the issue?  I'm not able to create any spontaneous destruction with the CS-R2 and I believe that some fixes I've made for other instabilities might have fixed this issue as well.

**Comment by KAmaia** [comment]
As soon as B9 has become 1.2 compatible, I will try this, and report my
findings.  Sadly, though neither shuttle is 1.2 compatible, yet.

**Comment by ferram4** [comment]
Well, in that case, since I haven't been able to cause the issue in any situation, I'm going to close this issue.  If you manage to cause it again, we'll re-open it then.

**Comment by KAmaia** [comment]
Ferram, I can confirm that this issue is closed.  Things are working great now.  Thanks!   Sorry for the long delay, I've not had internet for a little while.
