### ISSUE TITLE
KSP v1.3

### ISSUE THREAD

**Issue by geralddarden** [ferram4/Kerbal-Joint-Reinforcement#16]
Any word on when we can expect to see this mod updated for KSP 1.3? I tried using the latest release in v1.3 and it is not compatible.

**Comment by adityapurwa** [comment]
I am expecting this too, without this mod time warp just mess everything.

**Comment by ferram4** [comment]
It shouldn't be long, I just need some time to make sure that no behavior changed before I make a release.

**Comment by gomker** [comment]
No issues to report on my personal recompile so far, Large boats and IR parts behaving well

**Comment by LendaUrbana** [comment]
If you want someone to test, you can send it to me ..kkkk

**Comment by julianYaman** [comment]
When does the update coming out?

**Comment by linuxgurugamer** [comment]
@geralddarden ,Frankly, this isn't an issue, please stop wasting his time responding.

@ferram4 , take your time.  Someone posted an unofficial dll in the forum thread, not sure if you approve of that or not.

**Comment by 0142929** [comment]
this very cool mod needs to update for 1.3 :)

**Comment by Murdabenne** [comment]
@ferram4 already knows this needs a rebuild - and is already said he is working on it June 3rd (amongst many other priorities). He doesn't need to be pestered by repeated requests.  Perhaps this might need to be locked.

**Comment by 0142929** [comment]
where did you see repeated requests?
people just ask @ferram4 and very interested when the mod comes out and that's it.

**Comment by ericfriesen** [comment]
@ferram4 thank you for the release.
On a side note, when using 1.2.2, the AVC code directs user to download version for 1.3, which is not compatible to 1.2.2 if to take the incompatible mods detected screen serious.

**Comment by ferram4** [comment]
That's unfortunately not something I can fix.  The .version file here is set to limit things to 1.3+, so any changes need to happen on AVC's end.

**Comment by 0142929** [comment]
it works fine with 1.3
thanks @ferram4 :)
