### ISSUE TITLE
KJR 3.1.1 - Undocking issue

### ISSUE THREAD

**Issue by Bezzier** [ferram4/Kerbal-Joint-Reinforcement#3]
Connection not broken between undocking craft. Can timewarp and vehicle separate, but when returning from the timewarp, upon physics load, they smash into one another, causing rapid unplanned disassembly.

**Comment by Bezzier** [comment]
Should mention..  x86 version of KSP 0.90. I eventually isolated KJR as the issue be uninstalling other possible culprits one at a time. Let me know what other information is needed.

**Comment by ferram4** [comment]
Should be fixed in the current dev build, which just needs some optimization before it is fully released.
