### ISSUE TITLE
Not working in Linux 64bit

### ISSUE THREAD

**Issue by siralhy** [ferram4/Kerbal-Joint-Reinforcement#6]
Looks like a wrong check in CompatibilityChecker.cs at line 194

192        public static bool IsWin64()
193        {
194            return (IntPtr.Size == 8) && (Environment.OSVersion.Platform == PlatformID.Win32NT);
195        }

as a result, it does not work in Linux 64 bit

**Comment by ferram4** [comment]
Which versions of linux report that their operating system is Windows?

**Comment by ferram4** [comment]
Based on the fact that there are apparently no versions of Linux64 that would report that they are windows, this line of code will never return true for Linux64.

**Comment by siralhy** [comment]
Sorry. 
Seems it was a problem with another mod. Vessels docked with Routine Mission Manager mod were not Joint-Reinforced. But it`s another story...
