### ISSUE TITLE
Crash on closing KSP

### ISSUE THREAD

**Issue by flurreh** [ferram4/Kerbal-Joint-Reinforcement#7]
As soon as I close KSP, there's a NullReferenceException which I could trace down to KJR, although I'm not really sure whether it's an issue with KJR or something else.

Stack trace:
`NullReferenceException: Object reference not set to an instance of an object
  at Versioning.get_version_minor () [0x00000] in <filename unknown>:0 
  at KerbalJointReinforcement.CompatibilityChecker.IsCompatible () [0x00000] in <filename unknown>:0 
  at KerbalJointReinforcement.CompatibilityChecker.IsAllCompatible () [0x00000] in <filename unknown>:0 
  at KerbalJointReinforcement.KJRManager.OnDestroy () [0x00000] in <filename unknown>:0 `

**Comment by ferram4** [comment]
Not an issue in KJR, but is an issue in the version of Compatibility Checker used.  Although I've never heard of it causing the game to outright crash.  I'll need the crash log and full reproduction steps for how to cause the game to actually crash on exit rather than simply print an exception to the log.

**Comment by flurreh** [comment]
https://www.dropbox.com/s/058rl7uew3ilhhj/2015-05-06_181734.zip?dl=0

I've put everything in there. Everything I did was closing the game. Maybe there's an issue with other mods, I will try reinstalling KSP later.

**Comment by ferram4** [comment]
There are no reproduction steps.  I want steps that will definitively cause the crash every single time so I can test whether or not any fixes work.

Does it require other mods in order to cause the issue?  Can the crash be reproduced only with KJR?  What is your memory usage at the time of crash?

**Comment by flurreh** [comment]
I'm unable to reproduce this now that I re-installed KSP including all my former mods. Doesn't seem to be any issue on your side.
