### ISSUE TITLE
Ship wobbles after docking

### ISSUE THREAD

**Issue by mossarelli** [ferram4/Kerbal-Joint-Reinforcement#9]
I used KJR and made a space plane that didn't wobble and flew very stable. I docked it at one of the stations orbiting Kerbin and then quit the game. After resuming the game today, my ship started wobbling while in Orbit and using the two RAPIER engines. I entered the atmosphere and all hell broke loose. It took me 8 minutes to wobble the thing down on the ground without blowing it up.

So I don't know the details but I can guess that docking and undocking from a station with a game relaunch in the middle destroys whatever reinforcement there was.

I'm going to go look for a solution to the wobble and remove it from the game completely.

**Comment by mossarelli** [comment]
Solved.
One need to go back into the Space Center after releasing from dock and then go back to the ship.
This might help you.

**Comment by ferram4** [comment]
This is very old, and should probably have been fixed by one of the numerous changes I've made since.  Closing, please make a new issue if it comes back.
